### ISSUE TITLE
preview yoksa li eklenmemeli

### ISSUE THREAD

**Issue by ademilter** [interacthings/framer-modules#10]
<img width="501" alt="screen shot 2015-09-01 at 15 47 55" src="https://cloud.githubusercontent.com/assets/187922/9604520/da0af4ec-50c0-11e5-9173-72c277a7cebd.png">

**Comment by burakcan** [comment]
Su an bunu eklemiyor olmamiz lazim.

**Comment by ademilter** [comment]
:+1:
